
program: src/completor.py
method: grid
parameters:
  dataset:
    value: 'humaneval'
  mode:
    value: 'buggy'
  model_name:
    value: 'incoder-6B'
  method:
    value: 'completion'
  part_id:
    values: [0,1,2,3,4,5,6,7]
  part_sz:
    value: 237
  large:
    value: 1
  start_index:
    value: 0
  end_index:
    value: -1
  use_wandb:
    value: 1